name: Real Estate Scraper

on:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 8:00 AM UTC
  workflow_dispatch:       # Optional manual trigger

jobs:
  scrape-and-send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          #TWILIO_SID: ${{ secrets.TWILIO_SID }}
          #TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          #TWILIO_FROM_WHATSAPP: ${{ secrets.TWILIO_FROM_WHATSAPP }}
          #TO_WHATSAPP: ${{ secrets.TO_WHATSAPP }}
        run: |
          python par.py
